# Generated by Django 6.0.3 on 2026-04-04 13:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('weekly_regular_hours', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('vacation_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('banked_hours_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('role', models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
