# Generated by Django 6.0.3 on 2026-04-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('entry_type', models.CharField(choices=[('work', 'Travail'), ('vacation', 'Vacances'), ('sick', 'Maladie'), ('holiday', 'Férié'), ('unpaid', 'Sans solde')], default='work', max_length=20)),
                ('morning_in', models.TimeField(blank=True, null=True)),
                ('lunch_out', models.TimeField(blank=True, null=True)),
                ('lunch_in', models.TimeField(blank=True, null=True)),
                ('day_shift_out', models.TimeField(blank=True, null=True)),
                ('evening_shift_in', models.TimeField(blank=True, null=True)),
                ('evening_shift_out', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.weeklytimesheet')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklytimesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'week_start'), name='unique_employee_week'),
        ),
        migrations.AddConstraint(
            model_name='dailyentry',
            constraint=models.UniqueConstraint(fields=('timesheet', 'day'), name='unique_day_per_timesheet'),
        ),
    ]
